### PR TITLE
Trim ssh public key before validation

### PR DESCRIPTION
**Pull request by mareklibra**

### CODE REVIEW

**Comment by mareklibra** [comment]
I don't like changing the value on the fly, the user might be confused. I would trim it again right before sending. wdyt?

**Comment by jtomasek** [comment]
`onBlur` happens when user leaves the field so it does not collide with the user input. Hmm, trimming it after submit would still require to trim in validation.

**Comment by ohadlevy** [comment]
> I don't like changing the value on the fly, the user might be confused. I would trim it again right before sending. wdyt?

I think thats the last thing I would expect, e.g. whats in the field is what I expect you to validate and send, so for me as a user I would go and manually change it before sending it... my vote is to trim it once you paste it in.

worth thinking of allowing multiple ssh keys, but I guess thats outside the scope of this pr..

**Comment by mareklibra** [comment]
Ok, the field is altered once the user changes focus. I keep the trimming in validation anyway for the case that the field already contains a value and the user adds extra whitespaces. Without it, the validation would be failing until the user clicks somewhere else.

**Pull request merged**
