### PR TITLE
Enhance Host installation progress for info stageStartedAt and stageUpdatedAt

### PR DESCRIPTION
**Pull request by mareklibra**

### CODE REVIEW

**Comment by mareklibra** [comment]
Considering the data recently received from backend, I am not sure if this change brings much value to the user.
It seems that the `stageUpdatedAt` works recently just for the `writing image` stage, since the sub-progress is updated during the process.

Otherwise even long-running stages (like the `waiting for control plane`) stay untouched long time till reaching next stage.

---


---


---


---

**Comment by mareklibra** [comment]
@andybraren Time passed, thoughts evolved, do we want something like this?

**Comment by andybraren** [comment]
Hm, it's been a while so I've lost some context, but displaying `Step started at` even if the `updated 3 seconds ago` part only appears for the `Writing image to disk` step still seems like it could be somewhat useful to me. WDYT @nirfarkas? Worth the additional text?

**Comment by nirfarkas** [comment]
LGTM

**Review by jtomasek — APPROVED** [review]

**Comment by mareklibra** [comment]
Rebased

**Review by jtomasek — APPROVED** [review]

**Pull request merged**
